// Auto-generated by scripts/fetch_cards.py -- do not hand-edit.
// Placeholder until the real fetch is run (see scripts/fetch_cards.py).
// Re-run the script to refresh. Newer sets are also covered live via the API fallback.
const CARDS_SNAPSHOT = "";
const CARDS = [];
