#!/usr/bin/env python3
"""
Fetch the full pokemontcg.io card catalog and write it as a compact cards.js
for the autocomplete's local dataset. Re-run this whenever you want to refresh
(e.g. after a new set releases) -- newer sets are also covered live via the
API fallback in index.html, so this is not strictly required, just faster.

Usage:
    python scripts/fetch_cards.py YOUR_API_KEY
    POKEMONTCG_API_KEY=... python scripts/fetch_cards.py
"""
import json
import os
import sys
import time
import urllib.request

API = "https://api.pokemontcg.io/v2/cards"
PAGE_SIZE = 250
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "cards.js")


def fetch_page(page, api_key):
    url = f"{API}?pageSize={PAGE_SIZE}&page={page}&select=name,number,set"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    if api_key:
        req.add_header("X-Api-Key", api_key)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def main():
    api_key = (sys.argv[1] if len(sys.argv) > 1 else None) or os.environ.get("POKEMONTCG_API_KEY")
    if not api_key:
        print("WARNING: no API key given -- this will be slow/throttled on the keyless tier.")
        print("  python scripts/fetch_cards.py YOUR_API_KEY")
        time.sleep(2)

    first = fetch_page(1, api_key)
    total = first.get("totalCount", 0)
    pages = (total + PAGE_SIZE - 1) // PAGE_SIZE
    print(f"totalCount={total} pages={pages}")

    rows = []
    seen = set()

    def add(data):
        for c in data:
            s = c.get("set") or {}
            name = c.get("name") or ""
            number = c.get("number") or ""
            total_n = s.get("printedTotal") or s.get("total") or ""
            set_name = s.get("name") or ""
            release = (s.get("releaseDate") or "").replace("/", "-")
            key = (name, number, set_name)
            if key in seen:
                continue
            seen.add(key)
            rows.append([name, number, total_n, set_name, release, name.lower()])

    add(first.get("data", []))
    for page in range(2, pages + 1):
        for attempt in range(5):
            try:
                data = fetch_page(page, api_key)
                add(data.get("data", []))
                break
            except Exception as e:
                wait = 5 * (attempt + 1)
                print(f"  page {page} failed ({e}), retrying in {wait}s...")
                time.sleep(wait)
        print(f"  page {page}/{pages} -> {len(rows)} rows so far")
        time.sleep(0.15 if api_key else 1.0)

    rows.sort(key=lambda r: r[4], reverse=True)  # newest sets first

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/fetch_cards.py -- do not hand-edit.\n")
        f.write(f"// Snapshot: {time.strftime('%Y-%m-%d')} | {len(rows)} cards\n")
        f.write("// Re-run the script to refresh. Newer sets are also covered live via the API fallback.\n")
        f.write("const CARDS_SNAPSHOT = " + json.dumps(time.strftime("%Y-%m-%d")) + ";\n")
        f.write("const CARDS = " + json.dumps(rows, separators=(",", ":"), ensure_ascii=False) + ";\n")

    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"Wrote {OUT_PATH} ({len(rows)} cards, {size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
